### ISSUE TITLE
Kernel Task stuck at 15% when finger rests on touchpad

### ISSUE THREAD

**Issue by adityahota** [xxxzc/xps15-9570-macos#73]
I see with the latest release that kernel task is taking up about 15% of CPU usage when my finger is resting on the trackpad. This was fixed earlier in a release but it looks like something has regressed.

Also, do you know if there is a way to disable the touchscreen as with the previous AML replacement?

**Comment by xxxzc** [comment]
Releases except 201208(use VoodooI2C 2.5.2) are using the same VoodooI2C 2.4.4 and SSDT-I2CX(SSDT-TPDX renamed).

You can copy https://raw.githubusercontent.com/xxxzc/xps15-9570-macos/ced5c266dc29c6c3de0efc9e87458f3e10677760/ACPI/SSDT-TPDX.dsl to SSDT-I2CX and uncomment `TPLT = Zero` to disable touchscreen.

**Comment by adityahota** [comment]
~Thanks--I was able to disable the touchscreen. However, it still looks like I am getting between 15 to 20% kernel task usage even at idle. Is anyone else getting that issue?~

~I tried changing the layout-id for AppleALC back to 72, but that didn't seem to affect anything.~

Looks like the usage went down a few minutes after restarting. I will keep an eye out!

**Comment by MaKS-NUC** [comment]
With the latest release 210110 kernel task is taking up about 14% of CPU usage when the finger is resting on the trackpad and about 12% when is resting on the touchscreen.

**Comment by adityahota** [comment]
Doing the steps to change SSDT-I2CX.aml (described by XXXZC) fixes the issue for me. I get 4 to 5 percent with my finger on trackpad and 2 percent without. Unfortunately, that disables touchscreen. 

let me know if you need a compiled version.

**Comment by xxxzc** [comment]
@MaKS-NUC @adityahota you can try to add the SSDT in https://github.com/xxxzc/xps15-9570-macos/issues/74#issuecomment-751622506 and remove https://github.com/xxxzc/xps15-9570-macos/blob/master/OC/config.plist#L202-L208 to enable interrupt mode on touchscreen.

**Comment by MaKS-NUC** [comment]
I tried described changes but the result is the same ~14% kernel task. I will continue with touchscreen disabled ~ 5% kernel task.

**Comment by MaKS-NUC** [comment]
One more thing:

I managed to get better performance without sacrifice battery life by modified CPUFrienDataProvider.kext, tested with Geekbench5.

With OLD CPUFriendDataProvider.kext the result is:
￼
<img width="865" alt="OLD_CPUFriendDataProvider" src="https://user-images.githubusercontent.com/57990307/104306189-4efefb80-54d6-11eb-8d81-d35e7d5c81f2.png">

With NEW CPUFriendDataProvider.kext the result is 10% better Since-Core Performance:

<img width="865" alt="NEW_CPUFriendDataProvider" src="https://user-images.githubusercontent.com/57990307/104306249-64742580-54d6-11eb-8a6d-eb3ba895f351.png">

And using VoltageShift (https://github.com/sicreative/VoltageShift) with these parameters:
￼
<img width="628" alt="VoltageShift" src="https://user-images.githubusercontent.com/57990307/104306363-866da800-54d6-11eb-8e7d-050c35a0a96b.png">

The result is more than 10% in Multi-Core Performance:

<img width="865" alt="NEW_Kext_and_Undervolt" src="https://user-images.githubusercontent.com/57990307/104306430-984f4b00-54d6-11eb-9565-adefe63dae38.png">
￼
I attached the modified kext for testing.

P.S. The CPU cooling system is repasted with Arctic MX-4 Thermal Compound.

[CPUFriendDataProvider.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5801595/CPUFriendDataProvider.kext.zip)
